export {default as Home} from './Home'
export {default as Footer} from './Footer'
export {default as Loader} from './Loader'
export {default as Navbar} from './Navbar'
export {default as SearchNews} from './SearchNews'
export {default as Menu} from './Menu'
export {default as NewsDetail} from './NewsDetail'
